version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: ia-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: IAgentDb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: /IAgent.API/Dockerfile
    container_name: ia-api
    restart: on-failure
    ports:
      - 5000:80
    depends_on:
      - mongo
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Mongo: "mongodb://admin:secret@mongo:27017/IAgentDb?authSource=admin"
      Kafka__BootstrapServers: "kafka:9092"

  billing:
    build:
      context: .
      dockerfile: /Billing.API/Dockerfile
    container_name: ia-billing
    restart: on-failure
    depends_on:
      - kafka
      - mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Mongo: "mongodb://admin:secret@mongo:27017/BillingDb?authSource=admin"
      Kafka__BootstrapServers: "kafka:9092"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ia-kafka
    ports:
    - 9092:9092
    - 29092:29092
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: "q1Sh-CLUSTER123456"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
  ia-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: ia-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mongo

